# Site settings
title: Devika Deonarine
email: devika.deonarine12@gmail.com
description: I am a Canadian based in London, self-identified feminist and gender policy expert
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devika.digital"

# Identity
your-name: Devika Deonarine
your-title: Senior Communications Officer

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: 
instagram_url: https://instagram.com/ddeviks
linkedin_url: https://www.linkedin.com/in/devika-deonarine-151a38148/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
